version: '3.8'

services:
  names_portfolio:
    container_name: names_portfolio
    build: .
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - NODE_ENV=production

networks:
  app_network:
    driver: bridge